"""Render a hardened docker-compose file + LiteLLM proxy config from a Manifest.

Topology:

  ┌────────────────────── agentbox_internal (internal: true, no egress) ─────┐
  │  agent-a ──┐                                                             │
  │  agent-b ──┼──►  llm-proxy (LiteLLM, :4000)  ──► provider API / local    │
  │            └──►  mcp-gateway (:8811)          ──► tool APIs              │
  └───────────────────────────────────────────────────────────────────────────┘
                     (only proxy + gateway are also on the egress network)

Agents have no route to the internet except through the proxy and gateway,
so cost caps, rate limits, allowlists and audit logs are all enforced at
choke points the agent cannot bypass.
"""

from __future__ import annotations

import secrets as pysecrets
from pathlib import Path

import yaml

from .manifest import AgentConfig, Manifest

INTERNAL_NET = "agentbox_internal"
EGRESS_NET = "agentbox_egress"
PROXY_PORT = 4000
GATEWAY_PORT = 8811
SQUID_PORT = 3128
NO_PROXY_HOSTS = "llm-proxy,mcp-gateway,localhost,127.0.0.1"

# Map manifest provider names -> LiteLLM model prefixes.
PROVIDER_PREFIX = {
    "anthropic": "anthropic/",
    "openai": "openai/",
    "gemini": "gemini/",
    "groq": "groq/",
    "bedrock": "bedrock/",
    "azure": "azure/",
    "ollama": "ollama/",
    "openai_compatible": "openai/",  # Docker Model Runner, vLLM, LM Studio…
}


def litellm_config(m: Manifest, virtual_key: str) -> dict:
    prefix = PROVIDER_PREFIX.get(m.model.provider, f"{m.model.provider}/")
    model_entry: dict = {
        "model_name": "agent-model",  # stable alias agents use; provider swaps are invisible
        "litellm_params": {"model": f"{prefix}{m.model.model}"},
    }
    if m.model.api_key_file:
        # LiteLLM reads env vars via os.environ/ prefix; we point it at a var
        # populated from the mounted secret file by the entrypoint wrapper.
        model_entry["litellm_params"]["api_key"] = "os.environ/LLM_API_KEY"
    if m.model.api_base:
        model_entry["litellm_params"]["api_base"] = m.model.api_base

    cfg: dict = {
        "model_list": [model_entry],
        "general_settings": {"master_key": virtual_key},
        "litellm_settings": {
            "max_budget": m.model.budget_usd,
            "budget_duration": m.model.budget_duration,
        },
    }
    router = {}
    if m.model.rpm:
        router["rpm"] = m.model.rpm
    if m.model.tpm:
        router["tpm"] = m.model.tpm
    if router:
        model_entry["litellm_params"].update(router)
    return cfg


def squid_conf(domains: list[str]) -> str:
    """Deny-by-default egress allowlist. Leading dots make squid match the
    domain and its subdomains; HTTPS passes through via CONNECT, filtered on
    the requested host — no TLS interception."""
    dotted = " ".join(d if d.startswith(".") else "." + d for d in domains)
    return (
        "# generated by agentbox — do not edit\n"
        f"http_port {SQUID_PORT}\n"
        "visible_hostname agentbox-egress\n"
        f"acl allowlist dstdomain {dotted}\n"
        "http_access allow allowlist\n"
        "http_access deny all\n"
        "cache deny all\n"
        # squid setuids to 'proxy', which can't write to the root-owned
        # /dev/stdout pipe — log to its own dir instead.
        "access_log stdio:/var/log/squid/access.log squid\n"
    )


def _egress_net(agent_name: str) -> str:
    return f"{EGRESS_NET}_{agent_name}"


def _egress_service(name: str, m: Manifest, root: Path) -> dict:
    """Per-agent allowlist proxy. It gets its own internal network so other
    agents can't borrow this agent's allowlist."""
    return {
        "image": "ubuntu/squid:latest",
        "networks": [_egress_net(name), EGRESS_NET],
        "volumes": [
            {"type": "bind",
             "source": str((root / f".agentbox/egress-{name}.conf").resolve()),
             "target": "/etc/squid/squid.conf", "read_only": True},
        ],
        "restart": "unless-stopped",
        "labels": {"agentbox.project": m.project, "agentbox.role": "egress-proxy",
                   "agentbox.agent": name},
    }


def _agent_service(name: str, a: AgentConfig, m: Manifest, virtual_key: str,
                   root: Path) -> dict:
    h = m.hardening
    svc: dict = {
        "image": a.image,
        "networks": [INTERNAL_NET],  # internal only — no direct egress, ever
        "volumes": [
            {
                "type": "bind",
                # Absolute: compose resolves relative paths against the compose
                # file's own directory (.agentbox/), not the project root.
                "source": str((root / a.workspace).resolve()),
                "target": "/workspace",
                "read_only": a.workspace_read_only,
            }
        ],
        "working_dir": "/workspace",
        "environment": {
            # The LLM-agnostic seam: standard OpenAI-compatible wiring.
            "OPENAI_BASE_URL": f"http://llm-proxy:{PROXY_PORT}/v1",
            "OPENAI_API_KEY": virtual_key,  # proxy virtual key, not a real credential
            "AGENT_MODEL": "agent-model",
            "MCP_GATEWAY_URL": f"http://mcp-gateway:{GATEWAY_PORT}/sse"
            if m.tools.mcp_servers
            else "",
            **a.env,
        },
        "deploy": {
            "resources": {
                "limits": {"cpus": str(a.limits.cpus), "memory": a.limits.memory,
                           "pids": a.limits.pids}
            }
        },
        "restart": "no",  # ephemeral by default
        "labels": {
            "agentbox.project": m.project,
            "agentbox.agent": name,
            "agentbox.ttl_minutes": str(a.limits.ttl_minutes),
        },
        "depends_on": ["llm-proxy"],
    }
    if a.command:
        svc["command"] = a.command
    if a.role:
        svc["environment"]["AGENT_ROLE"] = a.role
    if a.egress:
        proxy_url = f"http://egress-{name}:{SQUID_PORT}"
        svc["networks"].append(_egress_net(name))
        svc["environment"].update({
            "HTTP_PROXY": proxy_url, "http_proxy": proxy_url,
            "HTTPS_PROXY": proxy_url, "https_proxy": proxy_url,
            "NO_PROXY": NO_PROXY_HOSTS, "no_proxy": NO_PROXY_HOSTS,
        })
        svc["depends_on"].append(f"egress-{name}")
    if h.non_root:
        svc["user"] = "10001:10001"
    if h.read_only_rootfs:
        svc["read_only"] = True
        svc["tmpfs"] = [f"/tmp:size={h.tmpfs_size}"]
    if h.drop_all_capabilities:
        svc["cap_drop"] = ["ALL"]
    if h.no_new_privileges:
        svc["security_opt"] = ["no-new-privileges:true"]
    if m.tools.mcp_servers:
        svc["depends_on"].append("mcp-gateway")
    return svc


def compose(m: Manifest, virtual_key: str, root: Path = Path(".")) -> dict:
    services: dict = {}

    proxy: dict = {
        "image": "ghcr.io/berriai/litellm:main-stable",
        "networks": [INTERNAL_NET, EGRESS_NET],
        "volumes": [
            {"type": "bind",
             "source": str((root / ".agentbox/litellm.yaml").resolve()),
             "target": "/app/config.yaml", "read_only": True},
        ],
        "command": ["--config", "/app/config.yaml", "--port", str(PROXY_PORT)],
        "restart": "unless-stopped",
        "labels": {"agentbox.project": m.project, "agentbox.role": "llm-proxy"},
    }
    if m.model.api_key_file:
        proxy["secrets"] = ["llm_api_key"]
        # Read the secret file into the env var LiteLLM expects, inside the
        # container only — it never appears in compose config or `docker inspect`.
        proxy["entrypoint"] = ["/bin/sh", "-c",
                              'export LLM_API_KEY="$(cat /run/secrets/llm_api_key)" && '
                              'exec litellm --config /app/config.yaml --port ' + str(PROXY_PORT)]
        proxy.pop("command")
    services["llm-proxy"] = proxy

    if m.tools.mcp_servers:
        gw: dict = {
            "image": "docker/mcp-gateway:latest",
            "networks": [INTERNAL_NET, EGRESS_NET],
            "command": ["--transport=sse", f"--port={GATEWAY_PORT}",
                        f"--servers={','.join(m.tools.mcp_servers)}"],
            "restart": "unless-stopped",
            "labels": {"agentbox.project": m.project, "agentbox.role": "mcp-gateway"},
        }
        if m.tools.allow_docker_socket:
            gw["volumes"] = [{"type": "bind", "source": "/var/run/docker.sock",
                              "target": "/var/run/docker.sock"}]
        services["mcp-gateway"] = gw

    networks: dict = {
        INTERNAL_NET: {"internal": True},  # the whole point
        EGRESS_NET: {},
    }
    for name, a in m.agents.items():
        services[f"agent-{name}"] = _agent_service(name, a, m, virtual_key, root)
        if a.egress:
            services[f"egress-{name}"] = _egress_service(name, m, root)
            networks[_egress_net(name)] = {"internal": True}

    doc: dict = {
        "name": m.project,
        "services": services,
        "networks": networks,
    }
    if m.model.api_key_file:
        doc["secrets"] = {
            "llm_api_key": {"file": str((root / m.model.api_key_file).resolve())}
        }
    return doc


def new_virtual_key() -> str:
    return "sk-agentbox-" + pysecrets.token_urlsafe(24)


def write_all(m: Manifest, root: Path) -> tuple[Path, Path]:
    out = root / ".agentbox"
    out.mkdir(parents=True, exist_ok=True)
    (out / "secrets").mkdir(exist_ok=True)

    key_path = out / "virtual_key"
    if key_path.exists():
        virtual_key = key_path.read_text().strip()
    else:
        virtual_key = new_virtual_key()
        key_path.write_text(virtual_key)
        key_path.chmod(0o600)

    ll_path = out / "litellm.yaml"
    ll_path.write_text(yaml.safe_dump(litellm_config(m, virtual_key), sort_keys=False))

    for name, a in m.agents.items():
        if a.egress:
            (out / f"egress-{name}.conf").write_text(squid_conf(a.egress))

    compose_path = out / "compose.yaml"
    compose_path.write_text(yaml.safe_dump(compose(m, virtual_key, root), sort_keys=False))
    return compose_path, ll_path
